### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by smaragdus** [benedelstein/12ft-extension#1]
Hello,

Any chances to release this extension as CRX/ZIP archive?

Regards

**Comment by benedelstein** [comment]
no plans to, but I believe the creator of 12ft.io is working on an official browser extension.

**Comment by smaragdus** [comment]
@benedelstein 

Thank you for the quick response.

> I believe the creator of 12ft.io is working on an official browser extension.

I think it is unlikely that such an extension would make its way into [Chrome Web Store](https://chrome.google.com/webstore/category/extensions) but I hope if it comes into existence it will be published on GitHub or on another repository.

Regards
